### ISSUE TITLE
在matlab的代码里有一个疑问

### ISSUE THREAD

**Issue by tc-qaq** [YuanhaoGong/CurvatureFilter#9]
在matlab代码CF.m 中求梯度的时候：
function [gx, gy]=mygrad(im)
gx=[im(:,2)-im(:,1) (im(:,3:end)-im(:,1:end-2))./2 im(:,end)-im(:,end-1)];
gy=[im(2,:)-im(1,:) ; (im(3:end,:)-im(1:end-2,:))./2 ; im(end,:)-im(end-1,:)];

这里面中间部分是不是 应该把**(im(:,3:end)-im(:,1:end-2))./2** 改成 **(im(:,3:end-1)-im(:,2:end-2))./2**

**Comment by YuanhaoGong** [comment]
不是。边界上用的是向前向后差分，而里面用的是中心差分。你建议公式的是向后差分的一半？我感觉不是很合理。

Best,
Yuanhao Gong

--------------------------------------------------------------------------------
Computer Vision Lab, ETH Zurich

http://e-collection.library.ethz.ch/eserv/eth:47737/eth-47737-02.pdf

PhD, ETH Zurich, Switzerland
M.S., Xiamen University, China
B.S., Tsinghua University, China
--------------------------------------------------------------------------------

**Comment by tc-qaq** [comment]
我明白了，谢谢！
